'use client';

import { useState } from 'react';
import Link from 'next/link';
import Dropdown from '@/components/Dropdown';
import Button from '@/components/Button';
import Card from '@/components/Card';
import SkeletonLoader from '@/components/SkeletonLoader';

export default function LearnPage() {
  const [technology, setTechnology] = useState('');
  const [topic, setTopic] = useState('');
  const [depth, setDepth] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [hasStarted, setHasStarted] = useState(false);

  const technologies = ['Node.js', 'React', 'Java', 'SQL'];
  const topics = ['Event Loop', 'JWT', 'Indexing', 'Hooks', 'State Management', 'Database Design'];
  const depths = ['Beginner', 'Intermediate', 'Advanced'];

  const handleStartLearning = () => {
    if (technology && topic && depth) {
      setIsLoading(true);
      setHasStarted(true);
      setTimeout(() => setIsLoading(false), 1000);
    }
  };

  return (
    <main className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Learn Mode</h1>
          <p className="text-xl text-gray-600">
            Choose your learning path and dive deep into technical concepts
          </p>
        </div>

        {/* Selection Section */}
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <Dropdown
            label="Select Technology"
            options={technologies}
            value={technology}
            onChange={setTechnology}
            placeholder="Choose a technology"
          />
          <Dropdown
            label="Select Topic"
            options={topics}
            value={topic}
            onChange={setTopic}
            placeholder="Choose a topic"
          />
          <Dropdown
            label="Select Depth"
            options={depths}
            value={depth}
            onChange={setDepth}
            placeholder="Choose depth level"
          />
        </div>

        {/* Start Learning Button */}
        <div className="mb-12">
          <Button
            onClick={handleStartLearning}
            size="lg"
            variant="primary"
            className={`w-full md:w-auto ${
              !technology || !topic || !depth ? 'opacity-50 cursor-not-allowed' : ''
            }`}
          >
            Start Learning →
          </Button>
        </div>

        {/* Output Section */}
        {hasStarted && (
          <div className="space-y-8">
            <h2 className="text-3xl font-bold text-gray-900">
              {technology} - {topic} ({depth})
            </h2>

            {/* Concept Explanation */}
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">Concept Explanation</h3>
              {isLoading ? (
                <SkeletonLoader />
              ) : (
                <Card variant="default">
                  <div className="space-y-4">
                    <p className="text-gray-700 leading-relaxed">
                      This is a comprehensive explanation of the concept. In a real application, this would be generated by an AI model based on your selected technology, topic, and depth level. The explanation would include key definitions, important principles, and foundational knowledge needed to understand the topic.
                    </p>
                    <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                      <p className="font-mono text-sm text-gray-700">
                        // Code example related to {technology.toLowerCase()} and {topic.toLowerCase()}
                      </p>
                    </div>
                  </div>
                </Card>
              )}
            </div>

            {/* Real-world Example */}
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">Real-world Example</h3>
              {isLoading ? (
                <SkeletonLoader />
              ) : (
                <Card variant="default">
                  <div className="space-y-4">
                    <p className="text-gray-700 leading-relaxed">
                      Here's how this concept is applied in real-world applications and production systems. Understanding practical applications helps you connect theoretical knowledge with actual implementation scenarios.
                    </p>
                    <ul className="list-disc list-inside space-y-2 text-gray-700">
                      <li>Real-world scenario 1</li>
                      <li>Real-world scenario 2</li>
                      <li>Real-world scenario 3</li>
                    </ul>
                  </div>
                </Card>
              )}
            </div>

            {/* Common Interview Mistakes */}
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">Common Interview Mistakes</h3>
              {isLoading ? (
                <SkeletonLoader />
              ) : (
                <Card variant="highlighted">
                  <div className="space-y-4">
                    <div>
                      <h4 className="font-semibold text-gray-900 mb-2">❌ Mistake 1: Incomplete understanding</h4>
                      <p className="text-gray-700 text-sm">
                        Candidates often overlook the nuances of this concept, leading to incomplete or incorrect answers in interviews.
                      </p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-gray-900 mb-2">❌ Mistake 2: Lack of practical examples</h4>
                      <p className="text-gray-700 text-sm">
                        Not being able to provide real-world examples is a common issue that makes answers less convincing.
                      </p>
                    </div>
                    <div>
                      <h4 className="font-semibold text-gray-900 mb-2">❌ Mistake 3: Poor communication</h4>
                      <p className="text-gray-700 text-sm">
                        Failing to explain complex concepts in clear, simple terms can hurt your interview performance.
                      </p>
                    </div>
                  </div>
                </Card>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4 pt-8">
              <Button onClick={() => setHasStarted(false)} variant="outline">
                Start Over
              </Button>
              <Link href="/ask">
                <Button variant="secondary">
                  Ask More Questions
                </Button>
              </Link>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
